//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\kelvin.shen\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://fusion5d365demo2.api.crm6.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Mrxrm.D365.AzureWebJob.CurrencyUpdate.Models.D365" /out:"C:\Users\kelvin.shen\Source\Repos\mrxrm\Mrxrm\Mrxrm.Crm2016\Mrxrm.D365.AzureWebJob.CurrencyUpdate\Models.D365\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"admin@fusion5066.onmicrosoft.com" /password:"*********" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Mrxrm.D365.AzureWebJob.CurrencyUpdate.Models.D365
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.0.749")]
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext, ICrmServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Mrxrm.D365.AzureWebJob.CurrencyUpdate.Models.D365.Organization"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Mrxrm.D365.AzureWebJob.CurrencyUpdate.Models.D365.Organization> OrganizationSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Mrxrm.D365.AzureWebJob.CurrencyUpdate.Models.D365.Organization>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Mrxrm.D365.AzureWebJob.CurrencyUpdate.Models.D365.TransactionCurrency"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Mrxrm.D365.AzureWebJob.CurrencyUpdate.Models.D365.TransactionCurrency> TransactionCurrencySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Mrxrm.D365.AzureWebJob.CurrencyUpdate.Models.D365.TransactionCurrency>();
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
}